### ISSUE TITLE
[Enhancement] Add git tags to release builds

### ISSUE THREAD

**Issue by thomasgalliker** [thomasgalliker/Plugin.FirebasePushNotifications#134]
#### Summary
For better tracability of changes, it would be helpful to add git tags for each release build.

#### API Changes
Add another build step in azure-pipelines.yml which adds a git tag with the current semantic version.

**Comment by thomasgalliker** [comment]
Would you use something like GitTag@6 task to add git tags automatically to release builds?

```yml
- task: GitTag@6
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    workingdir: '$(System.DefaultWorkingDirectory)'
    tagUser: 'Azure Devops'
    tagEmail: '....'
    tag: 'v$(GitVersion.NuGetVersion)'
    forceTagCreation: true
```
